Add `extraPodLabels` to `oapInit` so Job can have additional labels
apache/skywalking-kubernetes pull request #125
Opened 2023-07-17 17:53 UTC by eric-futureself

Issue:  `oap-init` job is unable to be completed when `istio-injection: true` is set on a namespace.  The container specific to the job works, but the job does not mark as complete due to the lack of `istio-init` completing.

Solution: Add additional labels to `spec.template.metadata.labels` (e.g. `sidecar.istio.io/inject: false`), to the job-generated pod, which enables the job to complete properly when Istio is installed..

Unblock oap-init job from being blocked when Istio injection is enabled for a namespace

2023-07-18 01:20 UTC, kezhenxu94 approved these changes

2023-07-18 01:26 UTC, innerpeacez requested changes
The document needs to be updated, and empty value prompts should be provided in the `values.yaml` file.

2023-07-23 02:23 UTC, wu-sheng commented
@eric-futureself Any update?

2023-07-25 01:40 UTC, innerpeacez approved these changes
I'll continue with the document if @eric-futureself no response.

2023-07-25 03:25 UTC, merged